name: GitHub-Profile-3D-Contrib

on:
  #schedule: # 03:00 JST == 18:00 UTC
    #- cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile 3D Contrib
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기
          persist-credentials: false  # 수동으로 토큰 설정

      - name: Run GitHub Profile 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Update GitHub Profile 3D Contrib" || echo "No changes to commit"

      - name: Set Remote with Token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.repository.name }}.git

      - name: Pull with Rebase
        run: |
          git pull --rebase origin main

      - name: Push changes
        run: |
          git push origin main --force-with-lease
