name: GitHub-Profile-3D-Contrib

on:
  #schedule: # 03:00 JST == 18:00 UTC
    #- cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git

          # Unstaged changes 처리
          git add -A .
          git commit -m "temp commit for rebase" || echo "No changes to commit"

          # Rebase와 강제 푸시
          git fetch origin main
          git rebase origin/main || (git rebase --abort && echo "Rebase failed. Proceeding without rebase.")
          git push origin main --force-with-lease
